---
title: "RepairSeq_DamagingAgents"
output: html_document
---

```{r}
library("DiffBind")
library("ChIPpeakAnno")
library("ChIPseeker")
library("pqsfinder")
library("motifRG")
library("BSgenome.Hsapiens.UCSC.hg38")
library("EnsDb.Hsapiens.v86")
library("TxDb.Hsapiens.UCSC.hg38.knownGene")
library("clusterProfiler")
library("ReactomePA")
library("org.Hs.eg.db")
library("viridis")
library("ggplot2")
library("ggExtra")
library("ggpmisc")

txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
anno86 <- annoGR(EnsDb.Hsapiens.v86)

```

```{r}
### Load new dba and bcb objects.
load("repairseq_dbaV2.rdata")
#load("repairseq_bcbV2.rda")

# New masks basic 1D Peaks Common across H1 and H9
dba_H1H9_mask <- dba.mask(DBAobject,DBA_ID, c("H1","H9"))
dba_EdU_mask <- dba.mask(DBAobject,DBA_CONDITION, "EdU", mask=dba_H1H9_mask, merge="and")
dba_EdU_1Day_mask <- dba.mask(DBAobject,DBA_FACTOR,"1Day",mask=dba_EdU_mask, merge="and")
dba_EdU_1Day_Damage_mask <- dba.mask(DBAobject,DBA_TREATMENT,c("None","NCS"),mask=dba_EdU_1Day_mask, merge="and")
dba_EdU_1Day_Damage_ESCin_mask <- dba.mask(DBAobject,DBA_TISSUE,"ESC-iN",mask=dba_EdU_1Day_Damage_mask, merge="and")
dba_Damage <- dba(DBAobject,dba_EdU_1Day_Damage_ESCin_mask)
dba_Damage <- dba.contrast(dba_Damage, categories=DBA_TREATMENT, minMembers = 2)
dba_Damage <- dba.analyze(dba_Damage, method=DBA_DESEQ2)
dba_Damage_Report_NCS_None <- dba.report(dba_Damage, contrast=1, th=.05, bUsePval=TRUE)

dba.plotVolcano(dba_Damage, bUsePval = TRUE, th = .01)

```