---
title: "RepairSeq_Edu_EdC"
output: html_document
---

```{r}
library("DiffBind")
library("ChIPpeakAnno")
library("ChIPseeker")
library("pqsfinder")
library("motifRG")
library("BSgenome.Hsapiens.UCSC.hg38")
library("EnsDb.Hsapiens.v86")
library("TxDb.Hsapiens.UCSC.hg38.knownGene")
library("clusterProfiler")
library("ReactomePA")
library("org.Hs.eg.db")
library("viridis")
library("ggplot2")
library("ggExtra")
library("ggpmisc")

txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
anno86 <- annoGR(EnsDb.Hsapiens.v86)

```

```{r}
### Load new dba and bcb objects.
load("repairseq_dbaV2.rdata")
#load("repairseq_bcbV2.rda")

# New masks basic 1D Peaks Common across H1 and H9
dba_H1H9_mask <- dba.mask(DBAobject,DBA_ID, c("H1","H9"))
dba_EdU_EdC_mask <- dba.mask(DBAobject,DBA_CONDITION, c("EdU","EdC"), mask=dba_H1H9_mask, merge="and")
dba_EdU_EdC_1Day_mask <- dba.mask(DBAobject,DBA_FACTOR,c("1Day"),mask=dba_EdU_EdC_mask, merge="and")
dba_EdU_EdC_1Day_None_mask <- dba.mask(DBAobject,DBA_TREATMENT,"None",mask=dba_EdU_EdC_1Day_mask, merge="and")
dba_EdU_EdC_1Day_None_ESCin_mask <- dba.mask(DBAobject,DBA_TISSUE,"ESC-iN",mask=dba_EdU_EdC_1Day_None_mask, merge="and")
dba_1D_EdU_EdC <- dba(DBAobject,dba_EdU_EdC_1Day_None_ESCin_mask)
dba_1D_EdU_EdC <- dba.contrast(dba_1D_EdU_EdC, categories=DBA_CONDITION, minMembers = 2)
dba_1D_EdU_EdC <- dba.analyze(dba_1D_EdU_EdC, method=DBA_DESEQ2)
dba_1D_EdU_EdC_Report <- dba.report(dba_1D_EdU_EdC, contrast=1, th=1, bUsePval=TRUE)
#dba_1D_Common <- dba_1D_Report[dba_1D_Report$`p-value` > .05]

dba_EdU_EdU_EdC_mask <- dba.mask(DBAobject,DBA_CONDITION, c("EdU","EdU_EdC"), mask=dba_H1H9_mask, merge="and")
dba_EdU_EdU_EdC_1Day_mask <- dba.mask(DBAobject,DBA_FACTOR,c("1Day"),mask=dba_EdU_EdU_EdC_mask, merge="and")
dbaEdU_EdU_EdC_1Day_None_mask <- dba.mask(DBAobject,DBA_TREATMENT,"None",mask=dba_EdU_EdU_EdC_1Day_mask, merge="and")
dba_EdU_EdU_EdC_1Day_None_ESCin_mask <- dba.mask(DBAobject,DBA_TISSUE,"ESC-iN",mask=dbaEdU_EdU_EdC_1Day_None_mask, merge="and")
dba_1D_EdU_EdU_EdC <- dba(DBAobject,dba_EdU_EdU_EdC_1Day_None_ESCin_mask)
dba_1D_EdU_EdU_EdC <- dba.contrast(dba_1D_EdU_EdU_EdC, categories=DBA_CONDITION, minMembers = 2)
dba_1D_EdU_EdU_EdC <- dba.analyze(dba_1D_EdU_EdU_EdC, method=DBA_DESEQ2)
dba_1D_EdU_EdU_EdC_Report <- dba.report(dba_1D_EdU_EdU_EdC, contrast=1, th=1, bUsePval=TRUE)
```